import astroDtsBuilder from '@matthiesenxyz/astrodtsbuilder';
import {name} from '../package.json';

const config = astroDtsBuilder();

config.addSingleLineNote(
	`This file was generated by ${name}. Do not edit it directly.`
);
